// Shared destination catalogue — single source of truth
// Both Destinations.jsx and DestinationDetail.jsx import from here

export const DESTINATIONS = [
  { id: "builtin-dubai", region: "international", name: "Dubai", slug: "dubai", tag: "Luxury · Skyline", img: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80", budget: "luxury", theme: "family", description: "Experience the futuristic skyline, luxury shopping, and desert adventures. Dubai blends ultramodern architecture with rich Arabian culture — from the towering Burj Khalifa to traditional gold souks.", highlights: "Burj Khalifa, Desert Safari, Palm Jumeirah, Dubai Mall, Old Dubai, Atlantis, Global Village", best_time: "November – March", duration: "4–6 nights", price_from: "₹45,000", latitude: 25.2048, longitude: 55.2708 },
  { id: "builtin-bali", region: "international", name: "Bali", slug: "bali", tag: "Beaches · Culture", img: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80", budget: "mid", theme: "honeymoon", description: "A tropical paradise with terraced rice paddies, sacred temples, and world-class surfing. Bali offers an unmatched blend of nature, spirituality, and nightlife.", highlights: "Ubud Rice Terraces, Uluwatu Temple, Seminyak Beach, Tegallalang, Kuta, Mount Batur", best_time: "April – October", duration: "5–7 nights", price_from: "₹35,000", latitude: -8.3405, longitude: 115.092 },
  { id: "builtin-europe", region: "international", name: "Europe", slug: "europe", tag: "Classic · Heritage", img: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80", budget: "luxury", theme: "family", description: "Discover centuries of history across Paris, Rome, Switzerland, and beyond. Europe offers everything from Alpine adventures to Mediterranean coasts.", highlights: "Eiffel Tower, Swiss Alps, Colosseum, Santorini, Amsterdam, Prague", best_time: "May – September", duration: "10–15 nights", price_from: "₹1,20,000", latitude: 48.8566, longitude: 2.3522 },
  { id: "builtin-maldives", region: "international", name: "Maldives", slug: "maldives", tag: "Islands · Honeymoon", img: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1200&q=80", budget: "luxury", theme: "honeymoon", description: "Crystal-clear lagoons, overwater villas, and pristine white-sand beaches. The Maldives is the ultimate romantic getaway and luxury beach destination.", highlights: "Overwater Villas, Snorkeling, Sunset Cruises, Underwater Dining, Coral Reefs", best_time: "November – April", duration: "4–5 nights", price_from: "₹65,000", latitude: 3.2028, longitude: 73.2207 },
  { id: "builtin-thailand", region: "international", name: "Thailand", slug: "thailand", tag: "Beach · Adventure", img: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=1200&q=80", budget: "mid", theme: "friends", description: "From Bangkok's vibrant street food to Phi Phi's turquoise waters, Thailand is the perfect mix of adventure, culture, and affordability.", highlights: "Grand Palace, Phi Phi Islands, Phuket, Chiang Mai, Floating Markets, Krabi", best_time: "November – February", duration: "5–7 nights", price_from: "₹25,000", latitude: 13.7563, longitude: 100.5018 },
  { id: "builtin-singapore", region: "international", name: "Singapore", slug: "singapore", tag: "City · Family", img: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=1200&q=80", budget: "mid", theme: "family", description: "A compact city-state packed with futuristic gardens, world-class food, and family-friendly attractions. Clean, safe, and endlessly exciting.", highlights: "Marina Bay Sands, Gardens by the Bay, Sentosa, Singapore Zoo, Chinatown, Orchard Road", best_time: "Year-round", duration: "3–5 nights", price_from: "₹40,000", latitude: 1.3521, longitude: 103.8198 },
  { id: "builtin-goa", region: "domestic", name: "Goa", slug: "goa", tag: "Beach · Nightlife", img: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80", budget: "budget", theme: "friends", description: "India's favourite beach destination — Portuguese heritage, vibrant nightlife, water sports, and laid-back vibes on golden sands.", highlights: "Baga Beach, Fort Aguada, Dudhsagar Falls, Anjuna Flea Market, Old Goa Churches, Palolem", best_time: "October – March", duration: "3–5 nights", price_from: "₹8,000", latitude: 15.2993, longitude: 74.124 },
  { id: "builtin-manali", region: "domestic", name: "Manali", slug: "manali", tag: "Mountains · Adventure", img: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=80", budget: "budget", theme: "friends", description: "Nestled in the Himalayas, Manali offers snow-capped peaks, river rafting, and cozy mountain cafes. A gateway to Ladakh and Rohtang Pass.", highlights: "Rohtang Pass, Solang Valley, Old Manali, Hadimba Temple, Jogini Falls, Atal Tunnel", best_time: "March – June, Oct – Feb (snow)", duration: "4–6 nights", price_from: "₹7,000", latitude: 32.2396, longitude: 77.1887 },
  { id: "builtin-kashmir", region: "domestic", name: "Kashmir", slug: "kashmir", tag: "Snow · Serenity", img: "https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=1200&q=80", budget: "mid", theme: "honeymoon", description: "Paradise on Earth — houseboats on Dal Lake, snow-dusted Gulmarg, and the tulip gardens of Srinagar. Kashmir is pure magic.", highlights: "Dal Lake, Gulmarg, Pahalgam, Sonmarg, Mughal Gardens, Betaab Valley", best_time: "March – October", duration: "5–7 nights", price_from: "₹12,000", latitude: 34.0837, longitude: 74.7973 },
  { id: "builtin-kerala", region: "domestic", name: "Kerala", slug: "kerala", tag: "Backwaters · Nature", img: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80", budget: "mid", theme: "family", description: "God's Own Country — serene backwaters, lush tea plantations in Munnar, and Ayurvedic wellness retreats on the Malabar coast.", highlights: "Alleppey Backwaters, Munnar Tea Gardens, Fort Kochi, Thekkady, Varkala Beach", best_time: "September – March", duration: "5–7 nights", price_from: "₹10,000", latitude: 10.8505, longitude: 76.2711 },
  { id: "builtin-ladakh", region: "domestic", name: "Ladakh", slug: "ladakh", tag: "High Altitude · Biking", img: "https://images.unsplash.com/photo-1589556264800-08ae9e129a8c?auto=format&fit=crop&w=1200&q=80", budget: "mid", theme: "friends", description: "Dramatic landscapes of barren mountains, pristine lakes, and ancient monasteries. Ladakh is the ultimate road-trip and biking destination.", highlights: "Pangong Lake, Nubra Valley, Khardung La, Leh Palace, Magnetic Hill, Hemis Monastery", best_time: "June – September", duration: "6–8 nights", price_from: "₹15,000", latitude: 34.1526, longitude: 77.5771 },
  { id: "builtin-rajasthan", region: "domestic", name: "Rajasthan", slug: "rajasthan", tag: "Royal · Culture", img: "https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1200&q=80", budget: "luxury", theme: "family", description: "Land of kings — majestic forts, colourful bazaars, desert safaris, and palatial hotels. Rajasthan is India's most regal experience.", highlights: "Jaipur, Udaipur, Jodhpur, Jaisalmer, Pushkar, Ranthambore Tiger Reserve", best_time: "October – March", duration: "6–10 nights", price_from: "₹12,000", latitude: 26.9124, longitude: 75.7873 },
];

// Lookup helpers
export function getDestinationBySlug(slug) {
  return DESTINATIONS.find((d) => d.slug === slug) || null;
}

export function getDestinationById(id) {
  return DESTINATIONS.find((d) => d.id === id) || null;
}
